export const dummyCards = [
  {
    number: "#1",
    name: "Normal Wall",
    image: "./image/dommy/UTILITY_CARDS_NORMAL_WALL.png",
    price: 1,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#2",
    name: "$$",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_$$_TOWER.png",
    price: 20,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#3",
    name: "Boss Knocker",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_BOSS_KNOCKER.png",
    price: 20,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#4",
    name: "Grenade Launcher",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_GRENADE_LAUNCHER.png",
    price: 5,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#5",
    name: "Healing",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_HEALING_TOWER.png",
    price: 10,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#6",
    name: "Laser",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_LASER.png",
    price: 4,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#7",
    name: "Machine Gunner",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_MACHINE_GUNNER.png",
    price: 2,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#8",
    name: "Revealing",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_REVEALING_TOWER.png",
    price: 10,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#9",
    name: "Rocket Launcher",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_ROCKET_LAUNCHER.png",
    price: 6,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#10",
    name: "Shielding",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_SHIELDING_TOWER.png",
    price: 10,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#11",
    name: "Slowing",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_SLOWING_TOWER.png",
    price: 4,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#12",
    name: "Sniper",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_SNIPER.png",
    price: 4,
    collection: "vixens",
    special: "none",
  },
  {
    number: "#13",
    name: "Virus",
    image: "./image/dommy/VENGEFUL_VIXENS_CARDS_VIRUS_TOWER.png",
    price: 10,
    collection: "vixens",
    special: "none",
  } /* 
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  },
  {
    number: "#4879215",
    name: "Queen Healing Tower",
    image: "./image/dommy/dummyCard.png",
  }, */,
];
